/* Example device: the device side of its EVRe register map (evre-map/1), from example_device.json.
 * Generated by EVRe Studio: change the map, not this file.
 *
 * For the EVRe device library (lib/EVRe.h). The device bank 0xD000..0xD087 is served from
 * two images in address order, the read-only one (0xD000..0xD07F), then the read-write one
 * (0xD080..0xD087): the library's permission is one boundary, DEVICE_REG_WRITE_MIN.
 * The images hold the values as they go on the wire (raw, little endian): where a register has a
 * scale, shown = raw x scale + offset. A gap between registers reads 0.
 *
 * In one source file of the device:
 *
 *     example_device_ro_t ro;  // the device keeps it up to date
 *     example_device_rw_t rw;  // the host writes it; it starts at the map's defaults
 *     uint8_t protocolConfigure(base_t *dev) { return example_device_bind(dev, &ro, &rw); }
 *
 * or call example_device_bind() after protocolInit().
 * A host write lands in rw at once: compare rw with a copy after each packet to see what
 * changed, and apply it from there.
 *
 * What the map says and the library does not do, the device's part:
 *   limits      example_device_keep_limits() puts a write past them back:
 *               SETPOINT, FAN_SPEED
 *   persist     keep across a reset (EEPROM, flash) and load at start:
 *               FAN_SPEED
 *   login       the map's login at 0xF000 is not in the library
 *
 * Value names and bit fields: the C header export has them (_POS, _MSK).
 */
#ifndef EXAMPLE_DEVICE_TABLE_H
#define EXAMPLE_DEVICE_TABLE_H

#include <stddef.h>
#include <stdint.h>

#include "EVRe.h"

#define EXAMPLE_DEVICE_ID 0x1001u
#define EXAMPLE_DEVICE_SLAVE 1u
#define EXAMPLE_DEVICE_WRITE_MIN 0xd080u /* DEVICE_REG_WRITE_MIN */
#define EXAMPLE_DEVICE_READ_MAX 0xd087u /* DEVICE_REG_READ_MAX */
#define EXAMPLE_DEVICE_RO_SIZE 128u
#define EXAMPLE_DEVICE_RW_SIZE 8u

/* 0xD000..0xD07F, read-only: the device writes it */
typedef struct __attribute__((packed)) {
	uint32_t uptime; /* 0xD000 UPTIME, ms */
	float supply_v; /* 0xD004 SUPPLY_V, V */
	float supply_i; /* 0xD008 SUPPLY_I, A */
	float temperature; /* 0xD00C TEMPERATURE, °C */
	uint16_t state; /* 0xD010 STATE */
	uint16_t counter; /* 0xD012 COUNTER */
	int16_t pressure; /* 0xD014 PRESSURE, bar, shown = raw x 0.01 */
	uint8_t _gap_d016[106]; /* 0xD016..0xD07F: no register */
} example_device_ro_t;

/* 0xD080..0xD087, read-write: the host writes it */
typedef struct __attribute__((packed)) {
	float setpoint = 25.0f; /* 0xD080 SETPOINT, °C */
	uint8_t fan_speed = 30; /* 0xD084 FAN_SPEED, %, persist */
	uint8_t led_mode; /* 0xD085 LED_MODE */
	int16_t motor_speed; /* 0xD086 MOTOR_SPEED, rpm, danger */
} example_device_rw_t;

static_assert(sizeof(example_device_ro_t) == EXAMPLE_DEVICE_RO_SIZE, "the read-only image");
static_assert(offsetof(example_device_ro_t, uptime) == 0x0u, "UPTIME at 0xD000");
static_assert(offsetof(example_device_ro_t, supply_v) == 0x4u, "SUPPLY_V at 0xD004");
static_assert(offsetof(example_device_ro_t, supply_i) == 0x8u, "SUPPLY_I at 0xD008");
static_assert(offsetof(example_device_ro_t, temperature) == 0xcu, "TEMPERATURE at 0xD00C");
static_assert(offsetof(example_device_ro_t, state) == 0x10u, "STATE at 0xD010");
static_assert(offsetof(example_device_ro_t, counter) == 0x12u, "COUNTER at 0xD012");
static_assert(offsetof(example_device_ro_t, pressure) == 0x14u, "PRESSURE at 0xD014");
static_assert(sizeof(example_device_rw_t) == EXAMPLE_DEVICE_RW_SIZE, "the read-write image");
static_assert(offsetof(example_device_rw_t, setpoint) == 0x0u, "SETPOINT at 0xD080");
static_assert(offsetof(example_device_rw_t, fan_speed) == 0x4u, "FAN_SPEED at 0xD084");
static_assert(offsetof(example_device_rw_t, led_mode) == 0x5u, "LED_MODE at 0xD085");
static_assert(offsetof(example_device_rw_t, motor_speed) == 0x6u, "MOTOR_SPEED at 0xD086");

/* The device bank served from the images: return it from protocolConfigure(), or call it after
 * protocolInit(). The library reads and writes through a pointer per byte. */
inline uint8_t example_device_bind(base_t *dev, example_device_ro_t *ro, example_device_rw_t *rw) {
	static uint8_t *bank[EXAMPLE_DEVICE_READ_MAX - 0xd000u + 1u];
	if (dev == nullptr) return INSTANCE_IS_NULL;
	uint8_t *p = reinterpret_cast<uint8_t *>(ro);
	for (uint16_t i = 0; i < EXAMPLE_DEVICE_RO_SIZE; ++i) bank[i] = p + i;
	uint8_t *q = reinterpret_cast<uint8_t *>(rw);
	for (uint16_t i = 0; i < EXAMPLE_DEVICE_RW_SIZE; ++i) bank[EXAMPLE_DEVICE_RO_SIZE + i] = q + i;
	dev->SALVE_ID_REG = EXAMPLE_DEVICE_SLAVE;
	dev->DEVICE_ID = EXAMPLE_DEVICE_ID;
	dev->DEVICE_REG_READ_MAX = EXAMPLE_DEVICE_READ_MAX;
	dev->DEVICE_REG_WRITE_MIN = EXAMPLE_DEVICE_WRITE_MIN;
	dev->D000 = bank;
	return NO_ERROR;
}

/* A host write past a register's limits (the map's min and max, raw here), put back as it was:
 * seen is rw as the last pass left it. A special value is always let through. Returns how many
 * registers were put back. */
inline unsigned example_device_keep_limits(example_device_rw_t *rw, const example_device_rw_t *seen) {
	unsigned back = 0;
	if (!(rw->setpoint >= -20.0f && rw->setpoint <= 120.0f)) { /* SETPOINT */
		rw->setpoint = seen->setpoint;
		back++;
	}
	if (!(rw->fan_speed <= 100)) { /* FAN_SPEED */
		rw->fan_speed = seen->fan_speed;
		back++;
	}
	return back;
}

#endif /* EXAMPLE_DEVICE_TABLE_H */
