/* Example device: the device side of its EVRe register map (evre-map/1), from example_device.json.
 * Generated by evre export example_device.json --to table --lib 1.1. Change the map, not this file.
 *
 * For the EVRe device library 1.1 (lib/EVRe.h) with EVRe Guard's register checks
 * (lib/guard/evre_guard_desc.h). The device bank 0xD000..0xD087 is served from one image, in address
 * order, through 2 ranges: one per run of read-only or writable registers, so a read-only
 * register may come after a writable one. The image holds the values as they go on the wire (raw,
 * little endian): where a register has a scale, shown = raw x scale + offset. A gap reads 0.
 *
 * In one source file of the device:
 *
 *     example_device_image_t image;  // the device keeps its read-only registers up to date; the host writes the rest
 *     evre_guard_check_t check;
 *     uint8_t protocolConfigure(base_t *dev) { return example_device_bind(dev, &image); }
 *     after protocolInit():  example_device_check_init(&check, &dev)  (a bad table: the device bank takes no write)
 *     the write handler:     evre_guard_check_write(&check, d, off, data, cnt), or with a login
 *                            evre_guard_write_checked(&guard, &check, d, off, data, cnt)
 *
 * The ranges are set in protocolConfigure(): protocolInit() checks a range table only then.
 * EVRe Guard refuses a write past a register's limits, outside a closed set or with a reserved
 * bit set (15), and part of a number or a byte no register covers (3): then nothing is stored.
 * A write it lets through lands in the image at once.
 *
 * What the map says and neither the library nor the Guard does, the device's part:
 *   persist     keep across a reset (EEPROM, flash) and load at start:
 *               FAN_SPEED
 *   login       the map's login at 0xF000: EVRe Guard part 1 (lib/guard/evre_guard.h)
 *
 * Value names and bit fields: the C header export has them (_POS, _MSK).
 */
#ifndef EXAMPLE_DEVICE_TABLE_H
#define EXAMPLE_DEVICE_TABLE_H

#include <stddef.h>
#include <stdint.h>

#include "EVRe.h"
#include "evre_guard_desc.h"

#if !defined(EVRE_GUARD_TABLE_FORMAT) || EVRE_GUARD_TABLE_FORMAT != 1
#error "this file is for EVRe Guard table format 1"
#endif

#define EXAMPLE_DEVICE_ID 0x1001u
#define EXAMPLE_DEVICE_SLAVE 1u
#define EXAMPLE_DEVICE_READ_MAX 0xd087u /* the bank's last byte */
#define EXAMPLE_DEVICE_SIZE 136u
#define EXAMPLE_DEVICE_RANGES 2u

/* 0xD000..0xD087: the device bank */
typedef struct __attribute__((packed)) {
	uint32_t uptime; /* 0xD000 UPTIME, ms */
	float supply_v; /* 0xD004 SUPPLY_V, V */
	float supply_i; /* 0xD008 SUPPLY_I, A */
	float temperature; /* 0xD00C TEMPERATURE, °C */
	uint16_t state; /* 0xD010 STATE */
	uint16_t counter; /* 0xD012 COUNTER */
	int16_t pressure; /* 0xD014 PRESSURE, bar, shown = raw x 0.01 */
	uint8_t _gap_d016[106]; /* 0xD016..0xD07F: no register */
	float setpoint = 25.0f; /* 0xD080 SETPOINT, °C */
	uint8_t fan_speed = 30; /* 0xD084 FAN_SPEED, %, persist */
	uint8_t led_mode; /* 0xD085 LED_MODE */
	int16_t motor_speed; /* 0xD086 MOTOR_SPEED, rpm, danger */
} example_device_image_t;

static_assert(sizeof(example_device_image_t) == EXAMPLE_DEVICE_SIZE, "the image");
static_assert(offsetof(example_device_image_t, uptime) == 0x0u, "UPTIME at 0xD000");
static_assert(offsetof(example_device_image_t, supply_v) == 0x4u, "SUPPLY_V at 0xD004");
static_assert(offsetof(example_device_image_t, supply_i) == 0x8u, "SUPPLY_I at 0xD008");
static_assert(offsetof(example_device_image_t, temperature) == 0xcu, "TEMPERATURE at 0xD00C");
static_assert(offsetof(example_device_image_t, state) == 0x10u, "STATE at 0xD010");
static_assert(offsetof(example_device_image_t, counter) == 0x12u, "COUNTER at 0xD012");
static_assert(offsetof(example_device_image_t, pressure) == 0x14u, "PRESSURE at 0xD014");
static_assert(offsetof(example_device_image_t, setpoint) == 0x80u, "SETPOINT at 0xD080");
static_assert(offsetof(example_device_image_t, fan_speed) == 0x84u, "FAN_SPEED at 0xD084");
static_assert(offsetof(example_device_image_t, led_mode) == 0x85u, "LED_MODE at 0xD085");
static_assert(offsetof(example_device_image_t, motor_speed) == 0x86u, "MOTOR_SPEED at 0xD086");

/* The device bank served from the image: return it from protocolConfigure(), where protocolInit()
 * checks the ranges. One range per run of read-only or writable registers. */
inline uint8_t example_device_bind(base_t *dev, example_device_image_t *image) {
	static evre_range_t ranges[EXAMPLE_DEVICE_RANGES];
	if (dev == nullptr || image == nullptr) return INSTANCE_IS_NULL;
	uint8_t *p = reinterpret_cast<uint8_t *>(image);
	ranges[0] = { 0xd000u, 0x80u, p + 0x0u, 0u }; /* 0xD000..0xD07F, read-only */
	ranges[1] = { 0xd080u, 0x8u, p + 0x80u, 1u }; /* 0xD080..0xD087, read-write */
	dev->SALVE_ID_REG = EXAMPLE_DEVICE_SLAVE;
	dev->DEVICE_ID = EXAMPLE_DEVICE_ID;
	dev->D_RANGES = ranges;
	dev->D_RANGE_CNT = EXAMPLE_DEVICE_RANGES;
	return NO_ERROR;
}

/* The map's limits, raw and typed, for the device's own clamps and static_asserts. */
constexpr float EXAMPLE_DEVICE_SETPOINT_RAW_MIN = -20.0f;
constexpr float EXAMPLE_DEVICE_SETPOINT_RAW_MAX = 120.0f;
constexpr uint8_t EXAMPLE_DEVICE_FAN_SPEED_RAW_MIN = 0;
constexpr uint8_t EXAMPLE_DEVICE_FAN_SPEED_RAW_MAX = 100;

/* EVRe Guard's table: an entry for each register a host writes (the login's aside), each tied to
 * its member of the image. */
inline const evre_guard_table_t *example_device_guard_table() {
	static constexpr evre_guard_desc_t regs[] = {
		/* addr, size, type, flags, n_values, spare1, first_value, spare2, min, max, zero_bits */
		{ 0xD080u, 4u, EVRE_GUARD_F32, 0u, 0u, 0u, 0u, 0u, 0xC1A00000UL, 0x42F00000UL, 0x00000000UL }, /* SETPOINT: -20 .. 120 °C */
		{ 0xD084u, 1u, EVRE_GUARD_U8, 0u, 0u, 0u, 0u, 0u, 0x00000000UL, 0x00000064UL, 0x00000000UL }, /* FAN_SPEED: 0 .. 100 % */
		{ 0xD085u, 1u, EVRE_GUARD_U8, 0u, 0u, 0u, 0u, 0u, 0x00000000UL, 0x000000FFUL, 0x00000000UL }, /* LED_MODE: the type's full range */
		{ 0xD086u, 2u, EVRE_GUARD_I16, 0u, 0u, 0u, 0u, 0u, 0xFFFF8000UL, 0x00007FFFUL, 0x00000000UL }, /* MOTOR_SPEED: the type's full range */
	};
	static_assert(regs[0].addr == 0xd000u + offsetof(example_device_image_t, setpoint)
			&& regs[0].size == sizeof(example_device_image_t::setpoint), "SETPOINT: its entry is its member");
	static_assert(regs[1].addr == 0xd000u + offsetof(example_device_image_t, fan_speed)
			&& regs[1].size == sizeof(example_device_image_t::fan_speed), "FAN_SPEED: its entry is its member");
	static_assert(regs[2].addr == 0xd000u + offsetof(example_device_image_t, led_mode)
			&& regs[2].size == sizeof(example_device_image_t::led_mode), "LED_MODE: its entry is its member");
	static_assert(regs[3].addr == 0xd000u + offsetof(example_device_image_t, motor_speed)
			&& regs[3].size == sizeof(example_device_image_t::motor_speed), "MOTOR_SPEED: its entry is its member");
	static constexpr evre_guard_table_t table = { regs, nullptr, 4u, 0u };
	return &table;
}

/* After protocolInit(): the table checked against the device's ranges. */
inline uint8_t example_device_check_init(evre_guard_check_t *check, const base_t *dev) {
	return evre_guard_check_init(check, example_device_guard_table(), dev);
}

#endif /* EXAMPLE_DEVICE_TABLE_H */
